job-board-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :jobs do
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create]

  root to: "application#home"
end

job-board-master/app/models/favorite.rb
class Favorite < ActiveRecord::Base
  validates_presence_of :user, :job

  # What field is this an error on if it isn't unique?
  # validates_uniqueness_of :user, scope: [:job]
  validates_uniqueness_of :job, scope: [:user]

  belongs_to :user # defines favorite.user
  belongs_to :job  # defines favorite.job
  # def job
  #   Job.find_by_id(self.job_id)
  # end
end

job-board-master/app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  start_date  :date
#  end_date    :date
#  user_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Job < ActiveRecord::Base
  validates_presence_of :title, :description, :user_id, :salary, :location, :company, :jobtype

  def self.active
    now   = Date.today
    query = %{
      ( start_date IS NULL OR start_date <= ? ) AND
      ( end_date   IS NULL OR end_date  >= ? )
    }.squish

    where [query, now, now]
  end


  # belongs_to :user
  # ^- would define job.user
  def author
    User.find self.user_id
  end

  def self.search(search)
    search
    where("title ilike ? or description ilike ? or location ilike ? or jobtype ilike ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  end
end

job-board-master/app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :user
end

job-board-master/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # This defines user.jobs to be the relation of all of this
  #   user's jobs
  has_many :jobs

  # Defines user.favorites
  has_many :favorites
  has_many :favorited_jobs, through: :favorites,
    source: :job
  # ^- we want this to describe jobs that the user
  #   has favorited, but there is a name collision

  has_many :phones

  def has_favorited?(job)
    # favorited_jobs.to_a.any? { |fav| fav.job == job }
    favorites.where(job: job).exists?
  end
end

job-board-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def home
    redirect_to jobs_path
  end
end

job-board-master/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    # Because of the routing / url I have
    #   params[:job_id]
    @job = Job.find params[:job_id]
    current_user.favorites.create! job: @job
    redirect_to :back, notice: "Favorite stored"
  end

  def destroy
    @job = Job.find params[:job_id]
    # This assumes there is exactly one matching
    #   favorite
    @favorite = current_user.favorites.where(job: @job).first
    @favorite.delete
    redirect_to :back, alert: "Favorite removed"
  end
end

job-board-master/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  helper_method :sort_column, :sort_direction

  before_action :authenticate_user!, except: [:show]
  # before_action :authenticate_user!, only: [:new, :create]

  def index
    @jobs = Job.active
    @jobs = @jobs.search(params[:search]) if params[:search]
    @jobs = @jobs.order(sort_column + " " + sort_direction)
  end

  def show
    @job = Job.find params[:id]
  end

  def new
    @now = Time.now
    @job = Job.new(
      start_date: Time.now,
      end_date:   Time.now + 1.week
    )
  end

  def create
    # This does not set user_id to correspond to current user
    #   @job = Job.new create_params
    # This sets user_id for the newly created job
    @job = current_user.jobs.new create_params
    if @job.save
      # Saved the record, now show it?
      # By redirecting to the show action
      redirect_to @job, notice: "Your listing was created"
    else
      # Validation errors, redisplay form
      render :new # this just says to display the `new` view

      # This _would_ end up calling the new action, but that
      #   isn't what we want (no create data that way)
      # redirect_to new_job_path
    end
  end

  def edit
    # @job = Job.find params[:id]
    # raise "NOPE" if @job.user != current_user

    # only find jobs for current_user
    @job = current_user.jobs.find params[:id]
  end

  def update
    @job = current_user.jobs.find params[:id]
    # update sets all the attributes from this hash
    # and then calls save (so returns true iff the
    # object saved without validation errors)
    #   @job.title = params[:job][:title]
    #   @job.description = params[:job][:description]
    #   ...
    #   @job.save
    if @job.update update_params
      # Job was updated with new params
      redirect_to @job, notice: "Your notice was updated"
    else
      # Validation errors, redisplay
      render :edit
    end
  end

  def create_params
    params.require(:job).permit(:title, :description, :start_date, :end_date, :salary, :location, :company, :jobtype)
  end

  def update_params
    # For now, reuse
    create_params
  end

  private

  def sort_column
    Job.column_names.include?(params[:sort]) ? params[:sort] : "end_date"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

job-board-master/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
  end
end

job-board-master/app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class name
    # Translate rails conventions to bootstrap conventions
    case name.to_sym
    when :notice
      :success
    when :alert
      :error
    else
      name
    end
  end

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" :nil
    #ensure that the jobs table starts with end_date "asc"
    #and that when clicked sorts "desc" while anything else starts off "asc"
    if column == "end_date" && params[:sort].nil? && params[:direction].nil?
      direction = "desc"
    else
      direction = column == params[:sort] && params[:direction] == "asc" ? "desc" : "asc"
    end
    search = params[:search]
    link_to title, {:sort => column, :direction => direction, :search => search}, {:class =>  css_class}
  end
end

job-board-master/app/views/jobs/_form.html.haml
= form_for @job, class: "form" do |f|
  - if @job.errors.any?
    / Display errors
    %p There were errors!
    %ul
      - @job.errors.full_messages.each do |error|
        %li= error

  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control"

  .form-group
    = f.label :description
    = f.text_area :description, rows: 10, class: "form-control"

  .form-group
    = f.label :salary
    = f.text_field :salary, class: "form-control", placeholder: "$"

  .form-group
    = f.label :company
    = f.text_field :company, class: "form-control"

  .form-group
    = f.label :location
    = f.text_field :location, class: "form-control"

  .form-group
    = f.label "Job Type (Full-time, Part-time, Contract, etc)"
    %br
    = f.select :jobtype,  options_for_select(%w[Full-time Part-time Contract Internship]), {}, class: "form-control dropdown"

  .form-group
    = f.label :start_date
    = f.date_field :start_date, class: "form-control"

  .form-group
    = f.label :end_date
    = f.date_field :end_date, class: "form-control"

  %button.btn.btn-primary Post Job

job-board-master/app/views/jobs/edit.html.haml
%h1 Edit Job

= render partial: "form"

job-board-master/app/views/jobs/index.html.haml
.container.row
  .col-xs-2
    - if current_user
      = link_to "Post New Job", new_job_path, class: "btn btn-primary"

  .col-xs-5.col-xs-offset-5
    = form_tag jobs_path, method: "get" do
      = text_field_tag :search, params[:search], placeholder: "Search", class: "form-control"

%br
%br

%table.table.table-striped
  %thead
    %tr
      %th= sortable "title", "Title"
      %th= sortable "company"
      %th= sortable "jobtype", "Type"
      %th= sortable "location"
      %th= sortable "end_date", "Active Until"
  %tbody
    - @jobs.each do |job|
      %tr
        %td= link_to job.title, job
        %td= job.company
        %td= job.jobtype
        %td= job.location
        %td= job.end_date

job-board-master/app/views/jobs/new.html.haml
%h1 Post a New Job

%p It is now #{@now.strftime "%H:%M:%S"}

/ looks for _form.html.? in the same view folder
/ something_else/_form.html.?
= render partial: "form"

job-board-master/app/views/jobs/show.html.haml
= link_to "Back", jobs_path, class: "btn btn-default"
- if current_user.has_favorited?(@job)
  = link_to job_favorites_path(@job), class: "btn btn-success", method: :delete do
    %i.fa.fa-star
- else
  = link_to job_favorites_path(@job), class: "btn btn-danger", method: :post do
    %i.fa.fa-star-o

/ Ruby function that generates an a tag
- if current_user == @job.author
  = link_to "Edit", edit_job_path(@job), class: "btn btn-default"

/ Nests a inside a div w/ class .btn
/ .btn.btn-default= link_to "Google", "http://google.com"

/ Works
/ Haml tag with a class: %a.btn.btn-default { href: edit_job_path(@job) }


%h1
  = @job.title
  %small= @job.author.email

%h3
  = @job.location

.well
  = @job.description

.well

  = @job.jobtype
  = @job.company
  = @job.start_date
  = @job.end_date

job-board-master/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title JobBoard
    = stylesheet_link_tag "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"
    = stylesheet_link_tag "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css"
    = stylesheet_link_tag 'application', media: 'all'

    = javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"
    = javascript_include_tag "//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"
    = javascript_include_tag 'application'

    = csrf_meta_tags

  %body
    %nav.navbar.navbar-default
      .container
        .navbar-header
          = link_to "ATLRUG Jobs", root_path, class: "navbar-brand"

        %ul.nav.navbar-nav
          / Main links will go here

        %ul.nav.navbar-nav.pull-right
          - if current_user
            / Signed in
            %li= link_to current_user.email, edit_user_registration_path
            %li= link_to "Log out", destroy_user_session_path, method: :delete
          - else
            / Not signed in
            %li= link_to "Log in", new_user_session_path
            %li= link_to "Sign up", new_user_registration_path

    .container
      .flash
        - flash.each do |name, msg|
          %div{ :class => "alert alert-#{flash_class name}" }
            %a.close{ "data-dismiss" => "alert" } &times;
            %div{ :id => "flash_#{flash_class name}" }
              = msg

      = yield